In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sys
from sklearn import datasets    
from sklearn.model_selection import train_test_split

In [2]:
diabetes_dataset = datasets.load_diabetes()


In [3]:
diabetes_dataset

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [4]:
print(diabetes_dataset.keys())

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])


In [5]:
print('Shape of diabetes data: \n{}'.format(diabetes_dataset.data.shape))

Shape of diabetes data: 
(442, 10)


In [6]:
print('Data: \n{}'.format(diabetes_dataset.data))

Data: 
[[ 0.03807591  0.05068012  0.06169621 ... -0.00259226  0.01990842
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ... -0.03949338 -0.06832974
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ... -0.00259226  0.00286377
  -0.02593034]
 ...
 [ 0.04170844  0.05068012 -0.01590626 ... -0.01107952 -0.04687948
   0.01549073]
 [-0.04547248 -0.04464164  0.03906215 ...  0.02655962  0.04452837
  -0.02593034]
 [-0.04547248 -0.04464164 -0.0730303  ... -0.03949338 -0.00421986
   0.00306441]]


In [7]:
#Print all vales in numpy array
np.set_printoptions(threshold=sys.maxsize)
print('Data: \n{}'.format(diabetes_dataset.data))

Data: 
[[ 3.80759064e-02  5.06801187e-02  6.16962065e-02  2.18723550e-02
  -4.42234984e-02 -3.48207628e-02 -4.34008457e-02 -2.59226200e-03
   1.99084209e-02 -1.76461252e-02]
 [-1.88201653e-03 -4.46416365e-02 -5.14740612e-02 -2.63278347e-02
  -8.44872411e-03 -1.91633397e-02  7.44115641e-02 -3.94933829e-02
  -6.83297436e-02 -9.22040496e-02]
 [ 8.52989063e-02  5.06801187e-02  4.44512133e-02 -5.67061055e-03
  -4.55994513e-02 -3.41944659e-02 -3.23559322e-02 -2.59226200e-03
   2.86377052e-03 -2.59303390e-02]
 [-8.90629394e-02 -4.46416365e-02 -1.15950145e-02 -3.66564468e-02
   1.21905688e-02  2.49905934e-02 -3.60375700e-02  3.43088589e-02
   2.26920226e-02 -9.36191133e-03]
 [ 5.38306037e-03 -4.46416365e-02 -3.63846922e-02  2.18723550e-02
   3.93485161e-03  1.55961395e-02  8.14208361e-03 -2.59226200e-03
  -3.19914449e-02 -4.66408736e-02]
 [-9.26954778e-02 -4.46416365e-02 -4.06959405e-02 -1.94420933e-02
  -6.89906499e-02 -7.92878444e-02  4.12768238e-02 -7.63945038e-02
  -4.11803852e-02 -9.63461

In [8]:
#Print diabetes dataset as a Data Frame
pd.DataFrame(diabetes_dataset.data)

0         1         2         3         4         5         6  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

            7         8         9  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [9]:
#Print all values in a Data Frame
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.DataFrame(diabetes_dataset.data)

0         1         2         3         4         5         6  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
5   -0.092695 -0.044642 -0.040696 -0.019442 -0.068991 -0.079288  0.041277   
6   -0.045472  0.050680 -0.047163 -0.015999 -0.040096 -0.024800  0.000779   
7    0.063504  0.050680 -0.001895  0.066630  0.090620  0.108914  0.022869   
8    0.041708  0.050680  0.061696 -0.040099 -0.013953  0.006202 -0.028674   
9   -0.070900 -0.044642  0.039062 -0.033214 -0.012577 -0.034508 -0.024993   
10  -0.096328 -0.044642 -0.083808  0.008101 -0.103389 -0.090561 -0.013948   
11   0.027178  0.050680  0.017506 -0.033214 -0.007073  0.045972 -0.065491   
12   0.016281 -0.044642 -0.028840 -0.009113 -0.004321 -0.009769  0.044958   
13   0.005383  0.050680 -0.001895  0.008101 -0.004321 -0.015719 -0.002903   
14   0.045341 -0.044642 -0.025607 -0.012556  0.017694 -0.000061  0.081775   
15  -0.052738  0.050680 -0.018062  0.080401  0.089244  0.107662 -0.039719   
16  -0.005515 -0.044642  0.042296  0.049415  0.024574 -0.023861  0.074412   
17   0.070769  0.050680  0.012117  0.056301  0.034206  0.049416 -0.039719   
18  -0.038207 -0.044642 -0.010517 -0.036656 -0.037344 -0.019476 -0.028674   
19  -0.027310 -0.044642 -0.018062 -0.040099 -0.002945 -0.011335  0.037595   
20  -0.049105 -0.044642 -0.056863 -0.043542 -0.045599 -0.043276  0.000779   
21  -0.085430  0.050680 -0.022373  0.001215 -0.037344 -0.026366  0.015505   
22  -0.085430 -0.044642 -0.004050 -0.009113 -0.002945  0.007767  0.022869   
23   0.045341  0.050680  0.060618  0.031053  0.028702 -0.047347 -0.054446   
24  -0.063635 -0.044642  0.035829 -0.022885 -0.030464 -0.018850 -0.006584   
25  -0.067268  0.050680 -0.012673 -0.040099 -0.015328  0.004636 -0.058127   
26  -0.107226 -0.044642 -0.077342 -0.026328 -0.089630 -0.096198  0.026550   
27  -0.023677 -0.044642  0.059541 -0.040099 -0.042848 -0.043589  0.011824   
28   0.052606 -0.044642 -0.021295 -0.074528 -0.040096 -0.037639 -0.006584   
29   0.067136  0.050680 -0.006206  0.063187 -0.042848 -0.095885  0.052322   
30  -0.060003 -0.044642  0.044451 -0.019442 -0.009825 -0.007577  0.022869   
31  -0.023677 -0.044642 -0.065486 -0.081414 -0.038720 -0.053610  0.059685   
32   0.034443  0.050680  0.125287  0.028758 -0.053855 -0.012900 -0.102307   
33   0.030811 -0.044642 -0.050396 -0.002228 -0.044223 -0.089935  0.118591   
34   0.016281 -0.044642 -0.063330 -0.057314 -0.057983 -0.048912  0.008142   
35   0.048974  0.050680 -0.030996 -0.049280  0.049341 -0.004132  0.133318   
36   0.012648 -0.044642  0.022895  0.052858  0.008063 -0.028558  0.037595   
37  -0.009147 -0.044642  0.011039 -0.057314 -0.024960 -0.042963  0.030232   
38  -0.001882  0.050680  0.071397  0.097616  0.087868  0.075407 -0.021311   
39  -0.001882  0.050680  0.014272 -0.074528  0.002559  0.006202 -0.013948   
40   0.005383  0.050680 -0.008362  0.021872  0.054845  0.073215 -0.024993   
41  -0.099961 -0.044642 -0.067641 -0.108957 -0.074494 -0.072712  0.015505   
42  -0.060003  0.050680 -0.010517 -0.014852 -0.049727 -0.023547 -0.058127   
43   0.019913 -0.044642 -0.023451 -0.071085  0.020446 -0.010082  0.118591   
44   0.045341  0.050680  0.068163  0.008101 -0.016704  0.004636 -0.076536   
45   0.027178  0.050680 -0.035307  0.032201 -0.011201  0.001504 -0.010266   
46  -0.056370 -0.044642 -0.011595 -0.033214 -0.046975 -0.047660  0.004460   
47  -0.078165 -0.044642 -0.073030 -0.057314 -0.084126 -0.074277 -0.024993   
48   0.067136  0.050680 -0.041774  0.011544  0.002559  0.005889  0.041277   
49  -0.041840  0.050680  0.014272 -0.005671 -0.012577  0.006202 -0.072854   
50   0.034443 -0.044642 -0.007284  0.014987 -0.044223 -0.037326 -0.002903   
51   0.0

In [10]:
print(diabetes_dataset.target)

[151.  75. 141. 206. 135.  97. 138.  63. 110. 310. 101.  69. 179. 185.
 118. 171. 166. 144.  97. 168.  68.  49.  68. 245. 184. 202. 137.  85.
 131. 283. 129.  59. 341.  87.  65. 102. 265. 276. 252.  90. 100.  55.
  61.  92. 259.  53. 190. 142.  75. 142. 155. 225.  59. 104. 182. 128.
  52.  37. 170. 170.  61. 144.  52. 128.  71. 163. 150.  97. 160. 178.
  48. 270. 202. 111.  85.  42. 170. 200. 252. 113. 143.  51.  52. 210.
  65. 141.  55. 134.  42. 111.  98. 164.  48.  96.  90. 162. 150. 279.
  92.  83. 128. 102. 302. 198.  95.  53. 134. 144. 232.  81. 104.  59.
 246. 297. 258. 229. 275. 281. 179. 200. 200. 173. 180.  84. 121. 161.
  99. 109. 115. 268. 274. 158. 107.  83. 103. 272.  85. 280. 336. 281.
 118. 317. 235.  60. 174. 259. 178. 128.  96. 126. 288.  88. 292.  71.
 197. 186.  25.  84.  96. 195.  53. 217. 172. 131. 214.  59.  70. 220.
 268. 152.  47.  74. 295. 101. 151. 127. 237. 225.  81. 151. 107.  64.
 138. 185. 265. 101. 137. 143. 141.  79. 292. 178.  91. 116.  86. 122.
  72. 

In [11]:
pd.DataFrame(diabetes_dataset.target)

0
0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
5     97.0
6    138.0
7     63.0
8    110.0
9    310.0
10   101.0
11    69.0
12   179.0
13   185.0
14   118.0
15   171.0
16   166.0
17   144.0
18    97.0
19   168.0
20    68.0
21    49.0
22    68.0
23   245.0
24   184.0
25   202.0
26   137.0
27    85.0
28   131.0
29   283.0
30   129.0
31    59.0
32   341.0
33    87.0
34    65.0
35   102.0
36   265.0
37   276.0
38   252.0
39    90.0
40   100.0
41    55.0
42    61.0
43    92.0
44   259.0
45    53.0
46   190.0
47   142.0
48    75.0
49   142.0
50   155.0
51   225.0
52    59.0
53   104.0
54   182.0
55   128.0
56    52.0
57    37.0
58   170.0
59   170.0
60    61.0
61   144.0
62    52.0
63   128.0
64    71.0
65   163.0
66   150.0
67    97.0
68   160.0
69   178.0
70    48.0
71   270.0
72   202.0
73   111.0
74    85.0
75    42.0
76   170.0
77   200.0
78   252.0
79   113.0
80   143.0
81    51.0
82    52.0
83   210.0
84    65.0
85   141.0
86    55.0
87   134.0
88    42.0
89   111.0
90    98.0
91   164.0
92    48.0
93    96.0
94    90.0
95   162.0
96   150.0
97   279.0
98    92.0
99    83.0
100  128.0
101  102.0
102  302.0
103  198.0
104   95.0
105   53.0
106  134.0
107  144.0
108  232.0
109   81.0
110  104.0
111   59.0
112  246.0
113  297.0
114  258.0
115  229.0
116  275.0
117  281.0
118  179.0
119  200.0
120  200.0
121  173.0
122  180.0
123   84.0
124  121.0
125  161.0
126   99.0
127  109.0
128  115.0
129  268.0
130  274.0
131  158.0
132  107.0
133   83.0
134  103.0
135  272.0
136   85.0
137  280.0
138  336.0
139  281.0
140  118.0
141  317.0
142  235.0
143   60.0
144  174.0
145  259.0
146  178.0
147  128.0
148   96.0
149  126.0
150  288.0
151   88.0
152  292.0
153   71.0
154  197.0
155  186.0
156   25.0
157   84.0
158   96.0
159  195.0
160   53.0
161  217.0
162  172.0
163  131.0
164  214.0
165   59.0
166   70.0
167  220.0
168  268.0
169  152.0
170   47.0
171   74.0
172  295.0
173  101.0
174  151.0
175  127.0
176  237.0
177  225.0
178   81.0
179  151.0
180  107.0
181   64.0
182  138.0
183  185.0
184  265.0
185  101.0
186  137.0
187  143.0
188  141.0
189   79.0
190  292.0
191  178.0
192   91.0
193  116.0
194   86.0
195  122.0
196   72.0
197  129.0
198  142.0
199   90.0
200  158.0
201   39.0
202  196.0
203  222.0
204  277.0
205   99.0
206  196.0
207  202.0
208  155.0
209   77.0
210  191.0
211   70.0
212   73.0
213   49.0
214   65.0
215  263.0
216  248.0
217  296.0
218  214.0
219  185.0
220   78.0
221   93.0
222  252.0
223  150.0
224   77.0
225  208.0
226   77.0
227  108.0
228  160.0
229   53.0
230  220.0
231  154.0
232  259.0
233   90.0
234  246.0
235  124.0
236   67.0
237   72.0
238  257.0
239  262.0
240  275.0
241  177.0
242   71.0
243   47.0
244  187.0
245  125.0
246   78.0
247   51.0
248  258.0
249  215.0
250  303.0
251  243.0
252   91.0
253  150.0
254  310.0
255  153.0
256  346.0
257   63.0
258   89.0
259   50.0
260   39.0
261  103.0
262  308.0
263  116.0
264  145.0
265   74.0
266   45.0
267  115.0
268  264.0
269   87.0
270  202.0
271  127.0
272  182.0
273  241.0
274   66.0
275   94.0
276  283.0
277   64.0
278  102.0
279  200.0
280  265.0
281   94.0
282  230.0
283  181.0
284  156.0
285  233.0
286   60.0
287  219.0
288   80.0
289   68.0
290  332.0
291  248.0
292   84.0
293  200.0
294   55.0
295   85.0
296   89.0
297   31.0
298  129.0
299   83.0
300  275.0
301   65.0
302  198.0
303  236.0
304  253.0
305  124.0
306   44.0
307  172.0
308  114.0
309  142.0
310  109.0
311  180.0
312  144.0
313  163.0
314  147.0
315   97.0
316  220.0
317  190.0
318  109.0
319  191.0
320  122.0
321  230.0
322  242.0
323  248.0
324  249.0
325  192.0
326  131.0
327  237.0
328   78.0
329  135.0
330  244.0
331  199.0
332  270.0
333  164.0
334   72.0
335   96.0
336  306.0
337   91.0
338  214.0
339   95.0
340  216.0
341  263.0
342  178.0
343  113.0
344  200.0
345  139.0
346  139.0
347   88.0
348  148.0
349   88.0
350  243.0
351   71.0
352   77.0
353  109.0
354  272.0
355   60.0
356   54.0
357  221.0
358   90.0
359  311.0
360  281.0
361  182.0
362  321.0
363  

In [12]:
diabetes_dataset.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [13]:
diabetes_DF = pd.DataFrame(diabetes_dataset.data)
diabetes_DF.columns = diabetes_dataset.feature_names
diabetes_DF

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
5   -0.092695 -0.044642 -0.040696 -0.019442 -0.068991 -0.079288  0.041277   
6   -0.045472  0.050680 -0.047163 -0.015999 -0.040096 -0.024800  0.000779   
7    0.063504  0.050680 -0.001895  0.066630  0.090620  0.108914  0.022869   
8    0.041708  0.050680  0.061696 -0.040099 -0.013953  0.006202 -0.028674   
9   -0.070900 -0.044642  0.039062 -0.033214 -0.012577 -0.034508 -0.024993   
10  -0.096328 -0.044642 -0.083808  0.008101 -0.103389 -0.090561 -0.013948   
11   0.027178  0.050680  0.017506 -0.033214 -0.007073  0.045972 -0.065491   
12   0.016281 -0.044642 -0.028840 -0.009113 -0.004321 -0.009769  0.044958   
13   0.005383  0.050680 -0.001895  0.008101 -0.004321 -0.015719 -0.002903   
14   0.045341 -0.044642 -0.025607 -0.012556  0.017694 -0.000061  0.081775   
15  -0.052738  0.050680 -0.018062  0.080401  0.089244  0.107662 -0.039719   
16  -0.005515 -0.044642  0.042296  0.049415  0.024574 -0.023861  0.074412   
17   0.070769  0.050680  0.012117  0.056301  0.034206  0.049416 -0.039719   
18  -0.038207 -0.044642 -0.010517 -0.036656 -0.037344 -0.019476 -0.028674   
19  -0.027310 -0.044642 -0.018062 -0.040099 -0.002945 -0.011335  0.037595   
20  -0.049105 -0.044642 -0.056863 -0.043542 -0.045599 -0.043276  0.000779   
21  -0.085430  0.050680 -0.022373  0.001215 -0.037344 -0.026366  0.015505   
22  -0.085430 -0.044642 -0.004050 -0.009113 -0.002945  0.007767  0.022869   
23   0.045341  0.050680  0.060618  0.031053  0.028702 -0.047347 -0.054446   
24  -0.063635 -0.044642  0.035829 -0.022885 -0.030464 -0.018850 -0.006584   
25  -0.067268  0.050680 -0.012673 -0.040099 -0.015328  0.004636 -0.058127   
26  -0.107226 -0.044642 -0.077342 -0.026328 -0.089630 -0.096198  0.026550   
27  -0.023677 -0.044642  0.059541 -0.040099 -0.042848 -0.043589  0.011824   
28   0.052606 -0.044642 -0.021295 -0.074528 -0.040096 -0.037639 -0.006584   
29   0.067136  0.050680 -0.006206  0.063187 -0.042848 -0.095885  0.052322   
30  -0.060003 -0.044642  0.044451 -0.019442 -0.009825 -0.007577  0.022869   
31  -0.023677 -0.044642 -0.065486 -0.081414 -0.038720 -0.053610  0.059685   
32   0.034443  0.050680  0.125287  0.028758 -0.053855 -0.012900 -0.102307   
33   0.030811 -0.044642 -0.050396 -0.002228 -0.044223 -0.089935  0.118591   
34   0.016281 -0.044642 -0.063330 -0.057314 -0.057983 -0.048912  0.008142   
35   0.048974  0.050680 -0.030996 -0.049280  0.049341 -0.004132  0.133318   
36   0.012648 -0.044642  0.022895  0.052858  0.008063 -0.028558  0.037595   
37  -0.009147 -0.044642  0.011039 -0.057314 -0.024960 -0.042963  0.030232   
38  -0.001882  0.050680  0.071397  0.097616  0.087868  0.075407 -0.021311   
39  -0.001882  0.050680  0.014272 -0.074528  0.002559  0.006202 -0.013948   
40   0.005383  0.050680 -0.008362  0.021872  0.054845  0.073215 -0.024993   
41  -0.099961 -0.044642 -0.067641 -0.108957 -0.074494 -0.072712  0.015505   
42  -0.060003  0.050680 -0.010517 -0.014852 -0.049727 -0.023547 -0.058127   
43   0.019913 -0.044642 -0.023451 -0.071085  0.020446 -0.010082  0.118591   
44   0.045341  0.050680  0.068163  0.008101 -0.016704  0.004636 -0.076536   
45   0.027178  0.050680 -0.035307  0.032201 -0.011201  0.001504 -0.010266   
46  -0.056370 -0.044642 -0.011595 -0.033214 -0.046975 -0.047660  0.004460   
47  -0.078165 -0.044642 -0.073030 -0.057314 -0.084126 -0.074277 -0.024993   
48   0.067136  0.050680 -0.041774  0.011544  0.002559  0.005889  0.041277   
49  -0.041840  0.050680  0.014272 -0.005671 -0.012577  0.006202 -0.072854   
50   0.034443 -0.044642 -0.007284  0.014987 -0.044223 -0.037326 -0.002903   
51   0

In [14]:
print(diabetes_dataset.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

In [15]:
null_data = diabetes_DF[diabetes_DF.isnull().any(axis=1)]

In [16]:
diabetes_DF.isnull().any(axis=1).sum()

0

In [17]:
w = np.array([[1], [2], [3]])
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
a = x.dot(w)
b = np.array([11,12,13])
b = b.reshape(3,1)
print(a)
print(np.sum(a - b))

[[14]
 [32]
 [50]]
60


In [18]:

class LinearRegressionModel():
    def __init__(self, learning_rate, epoch):
        self.learning_rate = learning_rate
        self.epoch = epoch
        self.cost = []
        
    def Fit(self, X_train, y_train):
        self.X_train = np.copy(X_train)
        self.y_train = np.copy(y_train)
    
    def GradientDescent(self, X_train, y_train):
        weight = np.random.randn(X_train.shape[1], 1)
        bias = 1
        num_of_DataPoint = len(X_train)

        for epo in range(self.epoch):
            
            y_predicted = X_train.dot(weight) + bias
            y_train = y_train.reshape(y_train.shape[0],1)
            
            error = y_predicted - y_train
            cost_function = (1 / (2 * num_of_DataPoint)) * np.sum(error ** 2)
#             cost_function = 1 - (np.sum(error**2) / (sum((y_train - y_train.mean())**2)))
            self.cost.append(cost_function)
            
            
            weight_derivative = (1 / num_of_DataPoint) * ((X_train.T).dot((error)))
            weight = weight - (self.learning_rate * weight_derivative)
            
            bias_derivative = (1 / num_of_DataPoint) * sum(error)
            bias = bias - (self.learning_rate * bias_derivative)
                
            self.weight = weight
            self.bias = bias
            
            print('iteration: \n{}'.format(epo))
            print()
            print('weight: \n{}'.format(weight))
            print()
            print('bias: \n{}'.format(bias))
            print()
            print('cost: \n{}'.format(cost_function))    
            print('-------------------------------------\n') 
    
    def Predict(self, X_test):
        LinearRegressionModel.GradientDescent(self, self.X_train, self.y_train)
        prediction = X_test.dot(self.weight) + self.bias
        return prediction

In [19]:
# # class LinearRegressionModel():
# #     def __init__(self, learning_rate, epoch):
# #         self.learning_rate = learning_rate
# #         self.epoch = epoch
        
# #     def Fit(self, X_train, y_train):
# #         self.X_train = np.copy(X_train)
# #         self.y_train = np.copy(y_train)
    
# #     def GradientDescent(self, X_train, y_train):
# #         weight = np.ones((X_train.shape[1], 1))
# #         bias = 1
# #         num_of_DataPoint = len(X_train)
# # #         print('X_train: \n{}\n'.format(X_train))
# # #         print('X_train''shape: {}\n'.format(X_train.shape))
# # #         print('weight: \n{}\n'.format(weight))
        
# #         # y_predicted = X_train.dot(weight) + bias
# # #         print('y_predicted: \n{}\n'.format(y_predicted))
# # #         print('y_predicted''s shape: {}\n'.format(y_predicted.shape))
        
# # #         print('y_train: \n{}\n'.format(y_train))
# # #         print('y_train shape: {}\n'.format(y_train.shape))
        
        
# #         # y_predicted = y_predicted.T
# #         # print('y_predicted_transpose: \n{}\n'.format(y_predicted))
# #         # print(('error shape: {}\n'.format((y_train - y_predicted).shape)))
# #         # print('y_train - y_predicted: \n{}\n'.format(y_train - y_predicted))
        
        
# # #         cost_function = sum(sum(value**2 for value in (y_train - y_predicted)))
# # #         print('cost: \n{}\n'.format(cost_function))
        
        
        
        
# #         for epo in range(self.epoch):
# #             y_predicted = X_train.dot(weight) + bias
# #             y_predicted = y_predicted.T
# # #             y_predicted_transpose = y_predicted.transpose()
# # #             y_predicted_result = sum(y_predicted_transpose)
            
            
            
# # #             print("This is y_predicted_result: \n{}".format(y_predicted_result))
# # #             print()
# # #             print('this is y_train: \n{}'.format(y_train))
# # #             print()
# # #             print('this is y_train - y_predicted_resul: \n{}'.format(y_train - y_predicted_result))
# #             cost_function = (1 / (2 * num_of_DataPoint)) * sum(sum(value**2 for value in (y_train - y_predicted)))
            
            
# #             weight_derivative = ((1 / num_of_DataPoint) * ((y_train - y_predicted).dot(X_train))).T 
            
# # #             print('this is weight derivative: \n{}\n'.format(weight_derivative))

# #             weight = weight - (self.learning_rate * weight_derivative)
            
# #             bias_derivative = (1 / num_of_DataPoint) * sum(sum(y_train - y_predicted))
# #             bias = bias - (self.learning_rate * bias_derivative)
                
# #             self.weight = weight
# #             self.bias = bias
            
# #             # print('iteration: \n{}'.format(epo))
# #             # print()
# #             # print('weight: \n{}'.format(weight))
# #             # print()
# #             # print('bias: \n{}'.format(bias))
# #             # print()
# #             # print('cost: \n{}'.format(cost_function))    
# #             # print('-------------------------------------\n') 
    
# #     def Predict(self, X_test):
# #         LinearRegressionModel.GradientDescent(self, self.X_train, self.y_train)
# #         prediction = (X_test.dot(self.weight) + self.bias).transpose()
# #         return prediction









# class LinearRegressionModel():
#     def __init__(self, learning_rate, epoch):
#         self.learning_rate = learning_rate
#         self.epoch = epoch
#         self.cost = []
        
#     def Fit(self, X_train, y_train):
#         self.X_train = np.copy(X_train)
#         self.y_train = np.copy(y_train)
    
#     def GradientDescent(self, X_train, y_train):
#         weight = np.ones(X_train.shape[1])
#         bias = 1
#         num_of_DataPoint = len(X_train)

# #         print('X_train: \n{}\n'.format(X_train))
# #         print('X_train''shape: {}\n'.format(X_train.shape))
# #         print('weight: \n{}\n'.format(weight))
        
#         # y_predicted = X_train.dot(weight) + bias
# #         print('y_predicted: \n{}\n'.format(y_predicted))
# #         print('y_predicted''s shape: {}\n'.format(y_predicted.shape))
        
# #         print('y_train: \n{}\n'.format(y_train))
# #         print('y_train shape: {}\n'.format(y_train.shape))
        
        
#         # y_predicted = y_predicted.T
#         # print('y_predicted_transpose: \n{}\n'.format(y_predicted))
#         # print(('error shape: {}\n'.format((y_train - y_predicted).shape)))
#         # print('y_train - y_predicted: \n{}\n'.format(y_train - y_predicted))
        
        
# #         cost_function = sum(sum(value**2 for value in (y_train - y_predicted)))
# #         print('cost: \n{}\n'.format(cost_function))
        
        
        
        
#         for epo in range(self.epoch):
#             y_predicted = weight.dot(X_train.T) + bias
#             # y_predicted = y_predicted.T
#             # print('Y_predicted: \n{}\n'.format(y_predicted))
#             # print('y_train - y_predicted: \n{}\n'.format(y_train - y_predicted))
#             # print('sum y_train - y_predicted: \n{}\n'.format(sum(y_train - y_predicted)))
            
            
# #             print("This is y_predicted_result: \n{}".format(y_predicted_result))
# #             print()
# #             print('this is y_train: \n{}'.format(y_train))
# #             print()
# #             print('this is y_train - y_predicted_resul: \n{}'.format(y_train - y_predicted_result))
#             cost_function = (1 / (2 * num_of_DataPoint)) * sum(value**2 for value in (y_train - y_predicted))
#             self.cost.append(cost_function)
#             weight_derivative = (1 / num_of_DataPoint) * ((X_train.T).dot((y_predicted - y_train)))

            
#             # print('y_train - y_predicted).dot(X_train): \n{}\n'.format((y_train - y_predicted).dot(X_train).T))
#             # print('this is weight derivative: \n{}\n'.format(weight_derivative))

#             weight = weight - (self.learning_rate * weight_derivative)
#             # print('this is weight : \n{}\n'.format(weight))
            
#             bias_derivative = (1 / num_of_DataPoint) * sum(y_predicted - y_train)
#             bias = bias - (self.learning_rate * bias_derivative)
                
#             self.weight = weight
#             self.bias = bias
            
#             print('iteration: \n{}'.format(epo))
#             print()
#             print('weight: \n{}'.format(weight))
#             print()
#             print('bias: \n{}'.format(bias))
#             print()
#             print('cost: \n{}'.format(cost_function))    
#             print('-------------------------------------\n') 
    
#     def Predict(self, X_test):
#         LinearRegressionModel.GradientDescent(self, self.X_train, self.y_train)
#         prediction = (X_test.dot(self.weight) + self.bias).T
#         return prediction

In [20]:
X_train, X_test, y_train, y_test = train_test_split(diabetes_dataset.data, 
                                                  diabetes_dataset.target,
                                                  random_state = 0)

In [84]:
lr = LinearRegressionModel(1.5, 1000)
#lr.GradientDescent(X_train, y_train)
lr.Fit(X_train, y_train)
prediction = lr.Predict(X_test)
prediction.shape
print("y_test: {}\n".format(y_test))

iteration: 
0

weight: 
[[ 1.10678503]
 [ 0.10003172]
 [ 1.40311827]
 [ 2.62079488]
 [ 2.55259356]
 [ 0.08013675]
 [-3.60913367]
 [ 0.15583572]
 [ 2.59496292]
 [ 2.08911623]]

bias: 
[227.38206317]

cost: 
14523.322350106964
-------------------------------------

iteration: 
1

weight: 
[[ 2.16076586]
 [ 0.23089127]
 [ 5.13083972]
 [ 5.26953638]
 [ 3.82744413]
 [ 1.12683582]
 [-5.96333731]
 [ 2.59912551]
 [ 5.98530259]
 [ 4.31687826]]

bias: 
[114.19935714]

cost: 
5947.744178355322
-------------------------------------

iteration: 
2

weight: 
[[ 3.19329962]
 [ 0.54240736]
 [ 8.60535254]
 [ 7.72715553]
 [ 4.94881099]
 [ 1.96017583]
 [-8.31680701]
 [ 5.10099853]
 [ 9.31894026]
 [ 6.52944405]]

bias: 
[170.80198521]

cost: 
3778.6131041858957
-------------------------------------

iteration: 
3

weight: 
[[  4.2065016 ]
 [  0.74210871]
 [ 12.15480079]
 [ 10.23639479]
 [  6.10714644]
 [  2.86112997]
 [-10.62606192]
 [  7.51498843]
 [ 12.62284532]
 [  8.69949855]]

bias: 
[142.51029727]




weight: 
[[  42.32174286]
 [ -17.97235735]
 [ 242.07217246]
 [ 158.56845862]
 [  39.26682384]
 [  12.38303012]
 [-141.94790522]
 [ 124.58061721]
 [ 211.74357061]
 [ 116.29693346]]

bias: 
[152.35596836]

cost: 
1796.7206309178655
-------------------------------------

iteration: 
102

weight: 
[[  42.34036279]
 [ -18.39082275]
 [ 243.63117468]
 [ 159.45096399]
 [  39.15652409]
 [  12.05911152]
 [-142.6616075 ]
 [ 125.02162734]
 [ 212.95799788]
 [ 116.72231313]]

bias: 
[152.35855808]

cost: 
1792.7660922500618
-------------------------------------

iteration: 
103

weight: 
[[  42.35499129]
 [ -18.81121392]
 [ 245.17965516]
 [ 160.3254616 ]
 [  39.04188841]
 [  11.73141587]
 [-143.36753528]
 [ 125.4540692 ]
 [ 214.16221911]
 [ 117.139714  ]]

bias: 
[152.36112753]

cost: 
1788.873808605588
-------------------------------------

iteration: 
104

weight: 
[[  42.36569709]
 [ -19.23347916]
 [ 246.71772474]
 [ 161.19204794]
 [  38.92300751]
 [  11.40003346]
 [-144.06578743]
 [ 125.8780744

 [ 132.56027969]]

bias: 
[152.55786687]

cost: 
1562.2198947005818
-------------------------------------

iteration: 
212

weight: 
[[  30.63569894]
 [ -68.35292751]
 [ 368.83689827]
 [ 223.06104297]
 [  14.18862725]
 [ -33.14543123]
 [-189.44555284]
 [ 141.68552327]
 [ 304.38515788]
 [ 132.53864353]]

bias: 
[152.55918696]

cost: 
1561.0686044418903
-------------------------------------

iteration: 
213

weight: 
[[  30.47084455]
 [ -68.79535831]
 [ 369.67473874]
 [ 223.43664693]
 [  13.92714557]
 [ -33.56299344]
 [-189.68551924]
 [ 141.67704504]
 [ 304.96424507]
 [ 132.51534532]]

bias: 
[152.5605009]

cost: 
1559.9267568256978
-------------------------------------

iteration: 
214

weight: 
[[  30.30569995]
 [ -69.23706336]
 [ 370.50869063]
 [ 223.80985219]
 [  13.66592516]
 [ -33.97982757]
 [-189.9234063 ]
 [ 141.66719263]
 [ 305.54038454]
 [ 132.49040901]]

bias: 
[152.56180874]

cost: 
1558.794243662132
-------------------------------------

iteration: 
215

weight: 
[[  30.1402

cost: 
1490.179515563549
-------------------------------------

iteration: 
297

weight: 
[[  16.47014226]
 [-102.89278072]
 [ 428.45631179]
 [ 248.19285758]
 [  -6.27539704]
 [ -65.30917693]
 [-204.15801327]
 [ 137.89622183]
 [ 345.26156201]
 [ 126.51223715]]

bias: 
[152.65326679]

cost: 
1489.5706921784313
-------------------------------------

iteration: 
298

weight: 
[[  16.30931714]
 [-103.25878796]
 [ 429.04090846]
 [ 248.42388433]
 [  -6.48874676]
 [ -65.64250625]
 [-204.27932646]
 [ 137.83120344]
 [ 345.66280476]
 [ 126.40947592]]

bias: 
[152.6542015]

cost: 
1488.9661304425297
-------------------------------------

iteration: 
299

weight: 
[[  16.14874924]
 [-103.62382196]
 [ 429.623229  ]
 [ 248.65372735]
 [  -6.70138629]
 [ -65.97474282]
 [-204.39974098]
 [ 137.76598666]
 [ 346.06257649]
 [ 126.30627235]]

bias: 
[152.65513293]

cost: 
1488.3657965905343
-------------------------------------

iteration: 
300

weight: 
[[  15.98844112]
 [-103.98788275]
 [ 430.20328568]
 [

-------------------------------------

iteration: 
402

weight: 
[[   1.26967645]
 [-136.15112614]
 [ 479.3047922 ]
 [ 267.25130951]
 [ -24.8924731 ]
 [ -94.60479841]
 [-213.14729338]
 [ 130.80193459]
 [ 380.81848281]
 [ 114.343466  ]]

bias: 
[152.73635172]

cost: 
1444.1669469637736
-------------------------------------

iteration: 
403

weight: 
[[   1.14259516]
 [-136.42005115]
 [ 479.70228582]
 [ 267.39221199]
 [ -25.03534947]
 [ -94.83233782]
 [-213.20532004]
 [ 130.73695455]
 [ 381.10452129]
 [ 114.22162178]]

bias: 
[152.7370187]

cost: 
1443.8703038586923
-------------------------------------

iteration: 
404

weight: 
[[   1.01585232]
 [-136.68813259]
 [ 480.09838883]
 [ 267.53249765]
 [ -25.17763738]
 [ -95.05899626]
 [-213.26295526]
 [ 130.67208172]
 [ 381.38973473]
 [ 114.09976638]]

bias: 
[152.73768367]

cost: 
1443.5756121116087
-------------------------------------

iteration: 
405

weight: 
[[   0.88944766]
 [-136.95537232]
 [ 480.49310699]
 [ 267.67216979]
 [ -25.319

 [ 103.27642552]]

bias: 
[152.79010615]

cost: 
1423.579920452256
-------------------------------------

iteration: 
495

weight: 
[[  -9.15670915]
 [-157.80056279]
 [ 510.9851257 ]
 [ 278.08267409]
 [ -35.91920384]
 [-112.34769548]
 [-217.165422  ]
 [ 125.27641567]
 [ 404.29547586]
 [ 103.15935427]]

bias: 
[152.79061409]

cost: 
1423.4165055199924
-------------------------------------

iteration: 
496

weight: 
[[  -9.25431838]
 [-157.99923245]
 [ 511.27428944]
 [ 278.17769018]
 [ -36.01575939]
 [-112.50474716]
 [-217.19624584]
 [ 125.2229539 ]
 [ 404.51748294]
 [ 103.0423791 ]]

bias: 
[152.79112055]

cost: 
1423.2541271465889
-------------------------------------

iteration: 
497

weight: 
[[  -9.3516387 ]
 [-158.19723637]
 [ 511.56248498]
 [ 278.27231529]
 [ -36.11190562]
 [-112.66116056]
 [-217.22685593]
 [ 125.16961817]
 [ 404.73891525]
 [ 102.92550064]]

bias: 
[152.79162552]

cost: 
1423.0927783553175
-------------------------------------

iteration: 
498

weight: 
[[  -9.448

 [  90.86314074]]

bias: 
[152.83870616]

cost: 
1410.39381848621
-------------------------------------

iteration: 
607

weight: 
[[ -18.44588734]
 [-176.31736047]
 [ 538.0787882 ]
 [ 286.64299547]
 [ -44.55650429]
 [-126.46586303]
 [-219.53642005]
 [ 120.01980575]
 [ 425.98426917]
 [  90.75930384]]

bias: 
[152.83907254]

cost: 
1410.3124305365025
-------------------------------------

iteration: 
608

weight: 
[[ -18.51528364]
 [-176.45228749]
 [ 538.27857428]
 [ 286.70329936]
 [ -44.61691697]
 [-126.56455052]
 [-219.54967399]
 [ 119.97894545]
 [ 426.15228326]
 [  90.65559813]]

bias: 
[152.83943786]

cost: 
1410.2315358666272
-------------------------------------

iteration: 
609

weight: 
[[ -18.58446449]
 [-176.58673636]
 [ 538.4777109 ]
 [ 286.76336129]
 [ -44.6770837 ]
 [-126.66282184]
 [-219.56281652]
 [ 119.9381816 ]
 [ 426.31989506]
 [  90.55202373]]

bias: 
[152.83980211]

cost: 
1410.1511312763955
-------------------------------------

iteration: 
610

weight: 
[[ -18.6534

697

weight: 
[[ -23.89701338]
 [-186.7095029 ]
 [ 553.70228205]
 [ 291.20673912]
 [ -49.13310334]
 [-133.85525066]
 [-220.34840974]
 [ 116.69526543]
 [ 439.62453273]
 [  81.95840452]]

bias: 
[152.86802511]

cost: 
1404.6704634123228
-------------------------------------

iteration: 
698

weight: 
[[ -23.94930921]
 [-186.80686867]
 [ 553.85170616]
 [ 291.24874552]
 [ -49.17549099]
 [-133.92225689]
 [-220.35377426]
 [ 116.66196375]
 [ 439.76066349]
 [  81.86669304]]

bias: 
[152.86830589]

cost: 
1404.623140777539
-------------------------------------

iteration: 
699

weight: 
[[ -24.00143928]
 [-186.90387446]
 [ 554.00065295]
 [ 291.29058319]
 [ -49.21771927]
 [-133.98896944]
 [-220.3590716 ]
 [ 116.62873412]
 [ 439.89648416]
 [  81.77511464]]

bias: 
[152.86858585]

cost: 
1404.5760933331942
-------------------------------------

iteration: 
700

weight: 
[[ -24.05340407]
 [-187.00052143]
 [ 554.14912403]
 [ 291.33225279]
 [ -49.25978896]
 [-134.05538942]
 [-220.36430216]
 [ 116.595

785

weight: 
[[ -27.91565139]
 [-194.01929823]
 [ 565.18859705]
 [ 294.32394411]
 [ -52.33093486]
 [-138.74175462]
 [-220.60042277]
 [ 114.01568671]
 [ 450.50640791]
 [  74.39028378]]

bias: 
[152.88983436]

cost: 
1401.3933492739156
-------------------------------------

iteration: 
786

weight: 
[[ -27.95510978]
 [-194.08907229]
 [ 565.30159988]
 [ 294.35335535]
 [ -52.36192404]
 [-138.78678745]
 [-220.60112129]
 [ 113.98787919]
 [ 450.61829751]
 [  74.31001925]]

bias: 
[152.89005124]

cost: 
1401.3647072366336
-------------------------------------

iteration: 
787

weight: 
[[ -27.99444107]
 [-194.15857644]
 [ 565.41424734]
 [ 294.38264665]
 [ -52.39281034]
 [-138.83161059]
 [-220.60177917]
 [ 113.96012519]
 [ 450.72994389]
 [  74.2298808 ]]

bias: 
[152.89026749]

cost: 
1401.33622437378
-------------------------------------

iteration: 
788

weight: 
[[ -28.03364564]
 [-194.22781158]
 [ 565.52654059]
 [ 294.41181847]
 [ -52.42359428]
 [-138.87622483]
 [-220.60239663]
 [ 113.9324

bias: 
[152.90800574]

cost: 
1399.2492343154458
-------------------------------------

iteration: 
882

weight: 
[[ -31.20481303]
 [-199.65395094]
 [ 574.65580949]
 [ 296.6801258 ]
 [ -54.92651299]
 [-142.24040888]
 [-220.5098328 ]
 [ 111.54306951]
 [ 460.31767125]
 [  67.17449787]]

bias: 
[152.90816939]

cost: 
1399.2322148709104
-------------------------------------

iteration: 
883

weight: 
[[ -31.2335934 ]
 [-199.70134427]
 [ 574.73927512]
 [ 296.69979215]
 [ -54.94961169]
 [-142.26836968]
 [-220.5075258 ]
 [ 111.51970281]
 [ 460.40875565]
 [  67.10590961]]

bias: 
[152.90833256]

cost: 
1399.2152847667492
-------------------------------------

iteration: 
884

weight: 
[[ -31.26227951]
 [-199.74854313]
 [ 574.82248269]
 [ 296.71937552]
 [ -54.9726479 ]
 [-142.2961847 ]
 [-220.50519614]
 [ 111.49637489]
 [ 460.49965218]
 [  67.03743545]]

bias: 
[152.90849526]

cost: 
1399.1984434770095
-------------------------------------

iteration: 
885

weight: 
[[ -31.29087166]
 [-199.7955

iteration: 
977

weight: 
[[ -33.55596593]
 [-203.37401987]
 [ 581.54090008]
 [ 298.21749163]
 [ -56.8825108 ]
 [-144.31390602]
 [-220.20705555]
 [ 109.48037309]
 [ 468.19534159]
 [  61.14910862]]

bias: 
[152.92172531]

cost: 
1397.957381400582
-------------------------------------

iteration: 
978

weight: 
[[ -33.57698593]
 [-203.40564672]
 [ 581.60324652]
 [ 298.23051389]
 [ -56.90093671]
 [-144.33014984]
 [-220.20314013]
 [ 109.46018892]
 [ 468.27058108]
 [  61.09074539]]

bias: 
[152.92184899]

cost: 
1397.9469481849123
-------------------------------------

iteration: 
979

weight: 
[[ -33.59793592]
 [-203.43713396]
 [ 581.66540345]
 [ 298.243478  ]
 [ -56.9193251 ]
 [-144.34629056]
 [-220.19921274]
 [ 109.44003346]
 [ 468.34567341]
 [  61.0324831 ]]

bias: 
[152.92197231]

cost: 
1397.9365662087998
-------------------------------------

iteration: 
980

weight: 
[[ -33.61881613]
 [-203.46848209]
 [ 581.72737147]
 [ 298.25638417]
 [ -56.93767617]
 [-144.36232855]
 [-220.19527346

In [85]:
print(prediction)

[[239.21027197]
 [247.62114473]
 [165.03913714]
 [120.34764333]
 [185.96461322]
 [257.29729006]
 [112.41440333]
 [188.53538259]
 [156.01334971]
 [230.28996263]
 [161.83252289]
 [179.33450031]
 [109.62022594]
 [ 92.05166298]
 [243.51449357]
 [ 96.09993583]
 [149.94499777]
 [ 69.18131362]
 [101.03186075]
 [217.34562923]
 [196.98738543]
 [156.04553786]
 [159.10393439]
 [159.33420717]
 [198.62584357]
 [165.46256221]
 [116.35945467]
 [ 85.6250518 ]
 [185.53634098]
 [161.11213548]
 [174.45068248]
 [ 87.40916769]
 [145.05825514]
 [143.11447753]
 [141.27051474]
 [192.6457808 ]
 [162.02268714]
 [185.37854929]
 [132.41637313]
 [203.45999228]
 [ 83.30201297]
 [164.38520135]
 [142.8879992 ]
 [178.39523908]
 [179.54647773]
 [ 75.48201264]
 [137.4336598 ]
 [142.23864889]
 [121.58377507]
 [232.06334683]
 [158.41326208]
 [ 81.4158    ]
 [159.8378832 ]
 [154.70735689]
 [233.370877  ]
 [172.08938172]
 [188.21684567]
 [119.24087867]
 [133.62669729]
 [170.42535261]
 [208.85717471]
 [168.55326571]
 [161.38

In [22]:
from sklearn.linear_model import LinearRegression
lin_re = LinearRegression()
lin_re .fit(X_train, y_train)
prediction = lin_re .predict(X_test)
print(prediction)
print('actual values :\n{}'.format(y_test))
print()
print(lin_re.coef_)
print()
print(lin_re.score(X_test, y_test))

[241.84730258 250.12303941 164.96456549 119.11639346 188.23120303
 260.56079379 113.07583812 190.54117538 151.8883747  236.50848375
 168.76844138 180.52719713 109.16037049  90.20148392 244.73990469
  90.58113696 152.51268196  66.97735025  98.0467335  215.39557064
 197.70737206 160.9176914  162.88584001 158.25373793 202.44823294
 168.46663088 119.87243699  83.05669211 189.9839726  163.02279586
 177.07828326  82.6702699  144.53204953 146.07901596 141.73841253
 195.18658206 164.18043648 189.14768927 128.13330927 206.12996392
  82.64273523 164.94912645 144.46057692 182.0519825  178.41355601
  72.5504089  142.69750371 140.43671531 121.75256103 233.70553551
 162.07809758  76.90270416 155.68916375 156.64052259 238.11357481
 175.75735587 190.82555855 119.48230582 131.3142863  172.2453037
 214.44479397 171.30900357 156.69146772 110.9755974  257.79427463
 154.6473623   81.10560078 227.26610365 205.445138    46.92383044
  78.28098211 131.5335209  105.63850688 145.15896592 133.85511669
 189.317998

In [73]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, prediction)

3180.1988368427274

In [23]:
# X_train

In [24]:
# X_train[:,0]

In [25]:
# X_test

In [26]:
# y_train

In [27]:
# y_test

In [28]:
# print('X_train shape: {}'.format(X_train.shape))
# print('X_test shape: {}'.format(X_test.shape))


In [29]:
# X_train[:,1].shape

In [30]:
# X_train[:,1].reshape(X_train.shape[0],1)

In [31]:
# X_train[:,1].transpose()

In [32]:
# X_test.shape
# X_test

In [33]:
# lr = LinearRegressionModel(0.01, 1000)
# #lr.GradientDescent(X_train, y_train)
# lr.Fit(X_train, y_train)
# prediction = lr.Predict(X_test)
# prediction.shape

In [34]:
#  prediction

In [35]:
# print(lr.weight.shape)
# print(X_test.shape)

In [36]:
# print(y_test)
# y_test.shape

In [37]:

#lr.GradientDescent(X_train, y_train)
# X_train = np.array([1,2,3,4,5])
# y_train= np.array([5,7,9,11,13])



In [38]:
# lr = LinearRegressionModel(0.01, 10000)
# Salary_DataFrame = pd.read_csv('D:\Python Project\Linear Regression\salary_data.csv')
# Salary_Array_X = np.array(Salary_DataFrame['YearsExperience'])
# Salary_Array_y = np.array(Salary_DataFrame['Salary'])
# X_train, X_test, y_train, y_test = train_test_split(Salary_Array_X, Salary_Array_y, test_size=0.33, random_state=0)
# X_train = X_train.reshape(20,1)
# # print(X_train.T)
# # print(len(X_train))
# X_test = X_test.reshape(X_test.shape[0],1)
# print(X_test)

In [39]:
# lr.Fit(X_train, y_train)
# prediction = lr.Predict(X_test)
# print(prediction)
# print(y_test)

# #Visualize the model
# plt.scatter(X_test, y_test, color='red')
# plt.plot(X_test, prediction, color='blue')
# plt.xlabel('Work Experience')
# plt.ylabel('Salary')
# plt.title('Salary vs Experience')
# plt.show()

In [40]:
# from sklearn.metrics import mean_squared_error
# mean_squared_error(y_test, prediction)

In [41]:
# epoch = np.array(range(lr.epoch))
# plt.plot(epoch, lr.cost)
# plt.show

In [42]:
# from sklearn.linear_model import LinearRegression
# lin_re = LinearRegression()
# lin_re .fit(X_train, y_train)
# prediction = lin_re .predict(X_test)
# print(prediction)
# print('actual values :\n{}'.format(y_test))
# print()
# print(lin_re.coef_)
# print()
# print(lin_re.score(X_test, y_test))

In [43]:
# from sklearn.linear_model import LinearRegression
# lin_re = LinearRegression()
# lin_re .fit(X_train, y_train)
# prediction = lin_re .predict(X_test)
# print(prediction)
# print('actual values :\n{}'.format(y_test))
# print()
# print(lin_re.coef_)

In [44]:
# w = np.array([[1,2,3,4]])
# train = np.array([[4,5,6,7], [8,9,10,11], [1,2,3,4], [7,8,9,10]])
# print(w)
# print(train)


In [45]:
# print((w * train))
# print()
# print((w*train).T)
# print()
# print(sum((w*train).T))

In [46]:
# a = np.array([1,2,3])
# b = np.array(([4,5,6],
#              [7,8,9]))
# sum((a*b+4).transpose())

In [47]:
# epoch = 1000
# #weight = np.zeros((1, X_train.shape[1]))
# weight = np.array([1,2,3,4,5,6,7,8,9,10])
# weight

In [48]:
# bias = np.zeros((1, 1))
# bias

In [49]:
# X = np.array(([1,2,3,4,5,6,7,8,9,10],
#              [11,12,13,14,15,16,17,18,19,20]))
# y = weight*X+bias
# print(y)
# sum(y[0,:])

In [50]:
# y_transe = y.transpose()
# y_transe

In [51]:
# sum(y_transe)

In [52]:
# X_test = np.array([1,2])
# X_test * sum(y_transe)

In [53]:
# sum(X_test * sum(y_transe))

In [54]:
# a = np.array([1,2])
# b = np.array([3,4])
# b-a

In [55]:
# c = np.array([5,6])
# c*(b-a)

In [56]:
# sum(c*(b-a))

In [57]:
# sum(c)

In [58]:
# sum(a)

In [59]:
# # a = np.array(([1],
# #              [2]))
# a = np.array([1,2])
# b = np.array([4,5])
# a * b

In [60]:
# w = np.array([[1], [2], [3], [4]])
# print(w)
# print()
# training = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# print(training)
# print()
# y_predicted = training.dot(w)+2
# print(y_predicted)
# print()
# y_predicted = y_predicted.T
# print(y_predicted)

In [61]:
# train_y = np.array([[200,300,400]])
# print(train_y - y_predicted)

In [62]:
# y_predicted_transpose = y_predicted.T
# print(y_predicted_transpose)

In [63]:
# y_result = sum(y_predicted_transpose)
# print(y_result)

In [64]:
# y_test = np.array([[100,200,300]])
# print(y_test - y_result)

In [65]:
# a = sum(value**2 for value in (y_test - y_result))
# print(a)

In [66]:
# t = np.array([1,2])
# t1 = np.array([3,4])
# print(t*t1)

In [67]:
# a = np.array([1,2,3,4])
# print(sum(a))

In [68]:
# a = np.array([[1,2,3,4]])
# b = np.array([5,6,7,8])
# s = sum(sum(b-a))
# print(s)
# print(b - a)

In [69]:
# t = np.array([[5],[6],[7],[8]])
# d = np.array([1])
# print(t)
# print()
# r = t - d
# print(r)

In [70]:
# wei = np.array([[5],[6],[7],[8],[9]])
# wei_der = np.array([[1],[2],[3],[4],[5]])
# print(wei - wei_der)

In [71]:
train = np.array([[7,8,9]])
x = np.array([[1,2,3,4], [5,6,7,8], [3,2,5,4]])
re = train.dot(x)
re = re.T
print(re)
print()
print(re * 2)

[[ 74]
 [ 80]
 [122]
 [128]]

[[148]
 [160]
 [244]
 [256]]


In [72]:
a = np.array([1,2,3,4])
cost = sum(value**2 for value in a)
print(cost)

30
